name: Package VSIX

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build extension
        run: pnpm run vscode:prepublish
        
      - name: Install vsce
        run: npm install -g @vscode/vsce
        
      - name: Package extension
        run: vsce package --no-dependencies --out inline-sql-syntax-${{ github.sha }}.vsix
        
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package-${{ github.sha }}
          path: '*.vsix'
          retention-days: 7